# Einspielen

## Technik

Die folgenden Übungen werden immer paarweise ausgeführt und eignen sich deshalb besonders um ins Einspielen integriert zu werden.

### Angriff mit Nachwerfen

Um eine hohe Kadenz an Abwehr/Annahmebewegungen zu erreichen, hält der Angriffsspieler 2 Bälle. Der erste Ball wird zuerst locker, im Laufe der Übung immer fester angegriffen. Der zweite Ball wird dann relativ bald hoch nach geworfen (Dankeball). Der Verteidigungsspieler wehrt den angegriffenen Ball ab und nimmt den geworfenen Ball danach an. Der Angriffsspieler fängt den Abgewehrten Ball und greift den Dankeball direkt an und wirft darauf den gefangen Ball nach [@hauser2016].

##### Varianten {-}

* Der Dankeball wird zu kurz, nach links oder nach rechts geworfen um eine Bewegung des Abwehrspielers zu erzwingen.
* Die Angriffe werden härter oder gelobt.

### Ball ins Gesicht

2 Spieler, 1 Ball. Der Ball wird vom Angriffsspieler auf den Abwehrspieler geworfen. Der Angriffsspieler zielt auf den Bereich der zwischen unterer und oberer Abwehr liegt, um die Entscheidung für eine von beiden Techniken und der Ausführung zu trainieren.

### Werfen mit 3 Bällen

Als Paar aufstellen, der Angriffsspieler hat 3 Bälle und wirft diese nacheinander dem Abwehrspieler zu, der sie hoch abwehrt, sodass der Angriffsspieler die Bälle einen nach dem Anderen fangen und wieder zurück werfen kann.

##### Varianten {-}

* Die Übung kann beliebig erschwert werden, indem die Bälle kürzer, länger oder seitlich versetzt geworfen werden. Es ist dann auf die Linie großer Zeh, Knie, Schulter zu achten

* Es können aufeinander gestellte Bänke zwischen den Spielern aufgestellt werden um das Netzt zu simulieren

### Kurz, lang, kurz

Paarweise. Spieler 1 spielt langen Ball zu Spieler 2 und läuft nach. Spieler 2 spielt kurz vor sich zu Spieler 1, der wieder kurz zurück und kehrt auf seine ursprüngliche Position zurück. Spieler 2 spielt nun lang und läuft nun dem Ball nach und spielt den von Spieler 1 kurz gespielten Ball zurück und kehrt dann wieder zum Ursprung zurück. Und so weiter

##### Varianten {-}

* mit Baggern
* oberes Zuspiel im Sprung

### Lang, Mitte, Kurz

Paarweise, ein Angriffsspieler mit Rücken zum Netz und ein Abwehrspieler:

1. Langer Angriff
1. Mittel gelegt
1. kurz gelegt
1. Ein Zwischenspiel und von vorne

### Lang, kurz

Angriffsspieler mit rücken zum Netz greift lang an auf Abwehrspieler. Hohe Abwehr. Angriffsspieler legt den Ball kurz. Nach Zwischenspiel wieder langer Angriff usw.

##### Varianten {-}

* kurzer Ball muss im oberen  Zuspiel gespielt werden
* ...

### Zwischenspiel

Jeder Spieler spielt sich den Ball einmal selbst zu. Dabei gibt es verschiedene Varianten:

* Einmal kurzes oberes Zuspiel und lang zurück
* unteres Zuspiel und und oberes zurück
* kurzes oberes Zuspiel und um 180° drehen und über Kopf zurück
* unteres Zuspiel um 180° drehenh und über Kopf im oberen Zuspiel zurück
* Viele weitere Varianten denkbar


### Abwehr-Zuspiel-Angriff

Jeder Spieler wehrt den Ball zu sich selbst ab, spielt sich den Ball selbst zu und greift danach auf seinen Mitspieler an.


## Koordination

Koordinative Übungen können sowohl ins Einspielen als auch im Training integriert werden. Die Übungen sollten immer fordernd sein, sonst bewirken sie keinen Trainingseffekt.

### Parallel spielen mit 2 Bällen

Zwei Spieler spielen parallel mit 2 Bällen. Die Technik sollte vorgegeben werden. Zuerst oberes Zuspiel, unteres Zuspiel, oder abwechselnd.

### Spiel mit 3 Bällen

Zu zweit. Jeder Spieler hält einen Ball in der Hand. Mit einem dritten Ball wird hin und her gespielt. Der eigene Ball muss immer passend hochgeworfen und wieder gefangen werden.

### Ein Spieler 2 Bälle

Ein Spieler hält einen Ball in jeder Hand das gegenüber spielt einen Ball zu. Der Spieler mit den beiden Bällen in der Hand wirft diese rechtzeitig hoch um den vom Partner geworfenen Ball zu spielen und fängt anschließend seine eigenen Bälle wieder.

Die Übung kann dadurch erschwert werden, dass kleinere Gegenstände benutzt werden, z.B. Tennisbälle.

### Drei Spieler 4 Bälle

Wie Spielen mit Nachlaufen (\@ref(spielen-mit-nachlaufen)), allerdings hat jeder Spieler einen Ball in der Hand und wirft sich den Ball selbst zu, spielt unter dessen den Spielball, fängt seinen eigenen Ball und läuft dem Spielball nach.

### Zwei gegen Zwei mit 3 Bällen

Gespielt wird auf den (halben) 3-Meter-Raum jedes 2er Team hat einen (Team-) Ball und ein dritter (Spiel-) Ball wird mit 3 Berührungen normal ausgespielt. Die Schwierigkeit ist, dass keiner der beiden Bälle den Boden berühren darf. Der Teamball darf also nicht abgelegt werden. Der Teamball kann entweder sich selbst zugenworfen werden oder zum Teamkollegen, er darf aber nicht den Boden berühren. Für den Spielball zählen normale Volleyball regeln. Wenn einer der beiden Bälle den Boden berührt oder ein andere Fehler begangen wird, zählt der Punkt als verloren. Das Team das einen Fehler begangen hat wird durch das nächste wartende Team ersetzt.

##### Varianten {-}

* jeder Spieler hält einen Ball in der Hand
* 3 gegen 3 mit 5/7 Bällen


